- hosts: localhost
  connection: local

  tasks:
    - name: Create Fedora29 virtual machine
      kubevirt_vm:
        state: "{{ state | default('present') }}"
        name: "{{ meta.name | mandatory }}"
        namespace: "{{ meta.namespace | default('default') }}"
        memory: "{{ memory | default('1024Mi') }}"
        cpu_cores: "{{ cpu_cores | default(1) }}"
        labels: "{{ labels | default(omit) }}"
        cloud_init_nocloud: "{{ cloud_init | default(omit) }}"
        interfaces:
          - name: default
            bridge: {}
            network:
              pod: {}
        datavolumes:
          - name: fedora29
            source:
              http:
                url: kubevirt/fedora-cloud-container-disk-demo:lastest
            pvc:
              accessModes:
                - ReadWriteOnce
              storage: "{{ disk_size | default('20Gi') }}"
