apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fedora29s.guest.kubevirt.io
spec:
  group: guest.kubevirt.io
  names:
    kind: Fedora29
    listKind: Fedora29List
    plural: fedora29s
    singular: fedora29
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
